name: Build Symfony Artifact

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, xml, curl, zip, bcmath

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --ignore-platform-reqs

      - name: Dump environment for production
        run: composer dump-env prod
        env:
          APP_ENV: prod
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Create Symfony artifact
        run: |
          tar -czvf symfony-artifact-r1.tar.gz \
          --exclude=.git \
          --exclude=node_modules \
          --exclude=var/cache \
          --exclude=var/log \
          --exclude=tests \
          --exclude=.env \
          --exclude=docker \
          --exclude=docker-compose.yml \
          --exclude=README.md \
          --exclude='*.log' \
          --exclude='*.gitignore' \
          .
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: symfony-artifact
          path: symfony-artifact-r1.tar.gz
